#ifdef XBOXHDMI_LEGACY
#include "stm32f0xx_hal.h"
#include "stm32f0xx.h"
#define HI2C_ADV_INSTANCE I2C1
#define HI2C_ADV_INSTANCE_TIMING 0x2000090E

#define HI2C_XBOX_INSTANCE I2C1
#define HI2C_XBOX_INSTANCE_TIMING 0x2000090E

#define HUART_DEBUG_INSTANCE USART2

#define ADV_IRQ_LINE EXTI4_15_IRQn
#define ADV_IRQ_HANDLER EXTI4_15_IRQHandler
#define ADV_IRQ_PORT GPIOA
#define ADV_IRQ_PIN GPIO_PIN_9

#define STATUS_LED_PORT GPIOA
#define STATUS_LED_PIN GPIO_PIN_10

#define SPARE_GPIO_PORT GPIOA
#define SPARE_GPIO_PIN GPIO_PIN_6
#else
#include "stm32g0xx_hal.h"
#include "stm32g0xx.h"

#define HI2C_ADV_INSTANCE I2C2
#define HI2C_ADV_INSTANCE_TIMING 0x00303D5B

#define HI2C_XBOX_INSTANCE I2C1
#define HI2C_XBOX_INSTANCE_TIMING 0x00303D5B

#define HUART_DEBUG_INSTANCE USART1

#define ADV_IRQ_LINE EXTI0_1_IRQn
#define ADV_IRQ_HANDLER EXTI0_1_IRQHandler
#define ADV_IRQ_PORT GPIOB
#define ADV_IRQ_PIN GPIO_PIN_1

#define STATUS_LED_PORT GPIOB
#define STATUS_LED_PIN GPIO_PIN_2

#define SPARE_GPIO_PORT GPIOC
#define SPARE_GPIO_PIN GPIO_PIN_6
#endif